### ISSUE TITLE
Data logging

### ISSUE THREAD

**Issue by gionnirocket** [mkopa/speeed#1]
Any plans to add data logging such as that of the eggrider to the app?
![Screenshot_20210309-163746](https://user-images.githubusercontent.com/87367787/125435908-360d2665-2990-46e7-80b4-95b64f0d66c9.jpg)

**Comment by mkopa** [comment]
Indeed! Detailed data analysis will be in a separate tab. I only ask for your patience, as I have several other tasks lined up and I only work on the application on weekends for a few hours at a time.

**Comment by gionnirocket** [comment]
No worries at all.... this weekend will be just fine 😅😅
But honestly you have done an excellent job... and any additional features
are icing on an already much appreciated tool.

I'm sure that you must know that the new Bafangs have started to ship with
an upgraded CANBUS communication protocol.
Any plans to crack that?

**Comment by gionnirocket** [comment]
Good day.
Any progress on Bluetooth dongle?
Will Bluetooth be able to be used in parallel with stock display?
