### ISSUE TITLE
Connection via Bluetooth

### ISSUE THREAD

**Issue by deadrabbit87** [mkopa/speeed#11]
Hi,

your tool is really awesome! Thanks a lot for your work. 

You wrote, you will provide a connection via Bluetooth. How is the state?

BW Maximilian

**Comment by Sevy13** [comment]
Very good job... quand auront nous je Bluetooth même si il faut donner de l'argent
@Sevy13

**Comment by Vangel72** [comment]
Nice question, too, I would be interested to know.

Kind regards                                                               Angelo Varsallona

> Il giorno 2 mar 2022, alle ore 17:44, Sevy13 ***@***.***> ha scritto:
> 
> Very good job... quand auront nous je Bluetooth même si il faut donner de l'argent

**Comment by techjaw** [comment]
Hello, 
will this work with BAFANG DP E12.CAN? Man, it would be great, I would be happy to pay for such functionality.

**Comment by rayholland** [comment]
bluetooth could be achieved with this cheap uat2ble transceiver module (it's 5v, so it could be plugged directly into the bafang harness):
https://www.go2tech.nl/winkel/componenten/at-09-bluetooth-4-0-ble-module-cc2540-cc2541/

but this requires some code changes from Marcin.
@mkopa ,would you be interested in implementing this?

**Comment by MartinPicha68** [comment]
I would also like Bluetooth, can you make your version 1.3.2 available?
