### ISSUE TITLE
Feature Request: Bafang DPC 18 UART Eco/Sport modes support

### ISSUE THREAD

**Issue by koksny** [mkopa/speeed#3]
One of Bafang DPC 18 firmwares comes with so called 2x5 PAS mode settings, unfortunately the only difference between them can be utilized by users of Bafang Ultra motor. For everyone else, there is no difference, and the settings for both modes are fetched from modes 0, 2, 4, 6, 8 and 9. 

It would be great if we could instead use Speeed to program the unused slots for different values in either Eco or Sport mode, or at least get any configuration ability for them.

**Comment by CitizenDev** [comment]
Yes please. We need legal speed and unlimited off road speed fast toggle.
