### ISSUE TITLE
hardware switch

### ISSUE THREAD

**Issue by b4n241** [mkopa/speeed#6]
The unpractical side of the app is the need to disconnect display cable to use it. A good idea could be a small waterproof switch box with a "Y" configuration (could simply have 2 6pos dipswitch inside) to make easy switch between original display and smartphone link (or bluetooth link when available in future)

**Comment by gionnirocket** [comment]
👍

**Comment by Vangel72** [comment]
Thanks, Grazie.

Kind regards                                                               Angelo Varsallona
